// Resolves workflow steps, applying dynamic rules to generate request-specific step sequences
// Evaluates workflow rules to dynamically modify step sequences based on request context
import { prisma } from '../db';
import { WorkflowStep, Request } from '@prisma/client';
import { evaluateRules } from './RuleEvaluator';
import { RuleContext } from './workflow.rules';

export class StepResolver {
  /**
   * Resolves and returns the fully evaluated list of workflow steps for a request.
   * If the request is in DRAFT/SUBMITTED and rules alter the flow, it handles cloning
   * the template to store the request-specific dynamic steps.
   */
  public static async getStepsForRequest(requestId: string): Promise<WorkflowStep[]> {
    // 1. Fetch request with detail tables and current template steps
    const request = await prisma.request.findUniqueOrThrow({
      where: { id: requestId },
      include: {
        workflowTemplate: {
          include: {
            steps: {
              orderBy: { order: 'asc' },
            },
          },
        },
        requestedBy: {
          include: {
            department: true,
          },
        },
        purchaseDetail: true,
        leaveDetail: true,
        maintenanceDetail: true,
      },
    });

    // 2. Fetch the standard active base template for this request type
    const baseTemplate = await prisma.workflowTemplate.findFirst({
      where: { requestType: request.type, isActive: true },
      include: {
        steps: {
          orderBy: { order: 'asc' },
        },
      },
    });

    const baseSteps = baseTemplate ? baseTemplate.steps : request.workflowTemplate.steps;

    // 3. Construct rule context with requesterRole & numerical cost
    const ctx: RuleContext = {
      type: request.type,
      priority: request.priority,
      departmentCode: request.requestedBy.department.code,
      requesterRole: request.requestedBy.role,
      details: {
        estimatedCost:
          request.purchaseDetail?.estimatedCost != null
            ? Number(request.purchaseDetail.estimatedCost)
            : undefined,
        leaveType: request.leaveDetail?.leaveType,
        urgencyLevel: request.maintenanceDetail?.urgencyLevel,
        totalDays: request.leaveDetail?.totalDays,
      },
    };

    const adjustedSteps = evaluateRules(ctx, baseSteps);

    // 4. Check if rules modified the steps relative to baseSteps
    const stepsModified =
      adjustedSteps.length !== baseSteps.length ||
      adjustedSteps.some((step, idx) => step.approverRole !== baseSteps[idx]?.approverRole);

    if (!stepsModified) {
      // If request was previously linked to a dynamic template, revert to base template
      if (request.workflowTemplate.name.startsWith('Dynamic:') && baseTemplate) {
        await prisma.request.update({
          where: { id: requestId },
          data: { workflowTemplateId: baseTemplate.id },
        });
      }
      return baseSteps;
    }

    // 5. Steps are modified — check if existing dynamic template already matches
    if (request.workflowTemplate.name.startsWith('Dynamic:')) {
      const dynamicSteps = request.workflowTemplate.steps;
      const dynamicMatches =
        dynamicSteps.length === adjustedSteps.length &&
        adjustedSteps.every((step, idx) => step.approverRole === dynamicSteps[idx]?.approverRole);

      if (dynamicMatches) {
        return dynamicSteps;
      }
    }

    const dynamicTemplateName = `Dynamic: ${baseTemplate?.name || request.workflowTemplate.name} for ${request.referenceNumber}`;

    let targetTemplateId: string;

    if (request.workflowTemplate.name.startsWith('Dynamic:')) {
      targetTemplateId = request.workflowTemplate.id;
      // Delete old dynamic steps for this template
      await prisma.workflowStep.deleteMany({
        where: { templateId: targetTemplateId },
      });
    } else {
      // Find existing dynamic template by name or create a new one
      let existingDynamic = await prisma.workflowTemplate.findFirst({
        where: { name: dynamicTemplateName },
      });

      if (existingDynamic) {
        targetTemplateId = existingDynamic.id;
        await prisma.workflowStep.deleteMany({
          where: { templateId: targetTemplateId },
        });
      } else {
        const newTemplate = await prisma.workflowTemplate.create({
          data: {
            name: dynamicTemplateName,
            requestType: request.type,
            description: `Custom flow generated by rules engine for request ${request.referenceNumber}`,
            isActive: false,
          },
        });
        targetTemplateId = newTemplate.id;
      }

      await prisma.request.update({
        where: { id: requestId },
        data: { workflowTemplateId: targetTemplateId },
      });
    }

    // Save the new dynamic steps
    const savedSteps = await Promise.all(
      adjustedSteps.map((step) =>
        prisma.workflowStep.create({
          data: {
            templateId: targetTemplateId,
            stepName: step.stepName,
            order: step.order,
            approverRole: step.approverRole,
            isFinal: step.isFinal,
          },
        })
      )
    );

    return savedSteps.sort((a, b) => a.order - b.order);
  }

  /**
   * Retrieves the next step in the flow after the current step.
   */
  public static async getNextStep(
    requestId: string,
    currentStepId: string
  ): Promise<WorkflowStep | null> {
    const steps = await this.getStepsForRequest(requestId);
    const currentIdx = steps.findIndex((s) => s.id === currentStepId);

    if (currentIdx === -1 || currentIdx === steps.length - 1) {
      return null;
    }

    return steps[currentIdx + 1] || null;
  }
}
