// Resolves workflow steps, applying dynamic rules to generate request-specific step sequences
// Evaluates workflow rules to dynamically modify step sequences based on request context
import { prisma } from '../db';
import { WorkflowStep, Request } from '@prisma/client';
import { evaluateRules } from './RuleEvaluator';
import { RuleContext } from './workflow.rules';

export class StepResolver {
  /**
   * Resolves and returns the fully evaluated list of workflow steps for a request.
   * If the request is in DRAFT/SUBMITTED and rules alter the flow, it handles cloning
   * the template to store the request-specific dynamic steps.
   */
  public static async getStepsForRequest(requestId: string): Promise<WorkflowStep[]> {
    // 1. Fetch request with detail tables and template steps
    const request = await prisma.request.findUniqueOrThrow({
      where: { id: requestId },
      include: {
        workflowTemplate: {
          include: {
            steps: {
              orderBy: { order: 'asc' },
            },
          },
        },
        requestedBy: {
          include: {
            department: true,
          },
        },
        purchaseDetail: true,
        leaveDetail: true,
        maintenanceDetail: true,
      },
    });

    const isDynamic = request.workflowTemplate.name.startsWith('Dynamic:');

    // If the template is already dynamic/cloned, just return its steps directly from DB
    if (isDynamic) {
      return request.workflowTemplate.steps;
    }

    // Otherwise, evaluate rules to check if we need to insert dynamic steps
    const ctx: RuleContext = {
      type: request.type,
      priority: request.priority,
      departmentCode: request.requestedBy.department.code,
      details: {
        estimatedCost: request.purchaseDetail?.estimatedCost
          ? Number(request.purchaseDetail.estimatedCost)
          : undefined,
        leaveType: request.leaveDetail?.leaveType,
        urgencyLevel: request.maintenanceDetail?.urgencyLevel,
        totalDays: request.leaveDetail?.totalDays,
      },
    };

    const baseSteps = request.workflowTemplate.steps;
    const adjustedSteps = evaluateRules(ctx, baseSteps);

    // If the steps were adjusted (different length or different approvers),
    // clone the template and steps to make it request-specific.
    const stepsModified =
      adjustedSteps.length !== baseSteps.length ||
      adjustedSteps.some((step, idx) => step.approverRole !== baseSteps[idx]?.approverRole);

    if (stepsModified) {
      // Clone the template and save the dynamic steps
      const newTemplateName = `Dynamic: ${request.workflowTemplate.name} for ${request.referenceNumber}`;
      
      const newTemplate = await prisma.workflowTemplate.create({
        data: {
          name: newTemplateName,
          requestType: request.type,
          description: `Custom flow generated by rules engine for request ${request.referenceNumber}`,
          isActive: false, // Hidden from general list
        },
      });

      // Create new steps database records
      const savedSteps = await Promise.all(
        adjustedSteps.map((step) =>
          prisma.workflowStep.create({
            data: {
              templateId: newTemplate.id,
              stepName: step.stepName,
              order: step.order,
              approverRole: step.approverRole,
              isFinal: step.isFinal,
            },
          })
        )
      );

      // Link request to the new dynamic template
      await prisma.request.update({
        where: { id: requestId },
        data: { workflowTemplateId: newTemplate.id },
      });

      return savedSteps.sort((a, b) => a.order - b.order);
    }

    return baseSteps;
  }

  /**
   * Retrieves the next step in the flow after the current step.
   */
  public static async getNextStep(
    requestId: string,
    currentStepId: string
  ): Promise<WorkflowStep | null> {
    const steps = await this.getStepsForRequest(requestId);
    const currentIdx = steps.findIndex((s) => s.id === currentStepId);

    if (currentIdx === -1 || currentIdx === steps.length - 1) {
      return null;
    }

    return steps[currentIdx + 1] || null;
  }
}
